name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup show

      - name: Manage Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Check code formatting
        run: cargo fmt --check

      - name: Lint code
        run: cargo clippy

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup show

      - name: Manage Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install devtools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall,cargo-llvm-cov,cargo-nextest

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Run tests
        run: |
          cargo llvm-cov nextest --workspace --lcov --output-path lcov.info
          cargo llvm-cov report --summary-only

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          files: lcov.info
